### ISSUE TITLE
load converter plugin: load "kubernetes": could not read plugin

### ISSUE THREAD

**Issue by RonaldGalea** [pulumi/pulumi-converter-kubernetes#11]
### What happened?

Cannot get the plug-in to run at all.

### Example

Running a stat command to check the binary is there:

```sh
stat -f %z "$(pwd)"/.pulumi/plugins/converter-kubernetes-v0.2.1/pulumi-converter-kubernetes
142583585
```

Also check by running `pulumi ls`:

```sh
PULUMI_HOME="$(pwd)/.pulumi" pulumi plugin ls                                      
NAME        KIND       VERSION  SIZE    INSTALLED       LAST USED
kubernetes  converter  0.2.1    143 MB  58 minutes ago  58 minutes ago

TOTAL plugin cache size: 143 MB
```

Trying to run the converter:

```sh
PULUMI_HOME="$(pwd)/.pulumi" pulumi convert --from kubernetes --language typescript                   

Converting from kubernetes...
error: load converter plugin: load "kubernetes": could not read plugin [pwd_path/.pulumi/plugins/converter-kubernetes-v0.2.1/pulumi-converter-kubernetes] stdout: EOF
```

### Output of `pulumi about`

```
CLI          
Version      3.109.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
gcp     7.13.0
nodejs  unknown

Host     
OS       darwin
Version  14.3
Arch     arm64

Dependencies:
NAME                              VERSION
@types/node                       18.19.22
@typescript-eslint/eslint-plugin  7.1.1
@typescript-eslint/parser         7.1.1
eslint                            8.57.0
prettier                          3.2.5
typescript                        5.4.2
@pulumi/gcp                       7.13.0
@pulumi/pulumi                    3.109.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
I believe this issue is caused by the fact that the binaries of the converter were published from an ubunto machine on the GitHub worflow where as it should have been `macos-latest` (or any macos). 

The root cause is that `dotnet publish` doesn't sign macos binaries unless the command was run from a macos machine. 

Changing the workflow back to running on macos latest should fix the problem cc @rquitales

**Comment by rquitales** [comment]
I have verified that this now works in v0.2.2 of the Kubernetes converter plugin.
